# Generated by Django 4.1 on 2022-08-20 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(default='user', max_length=50),
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='sga_user',
        ),
    ]
