# Generated by Django 4.1 on 2022-09-01 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_role_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='project',
        ),
    ]
