# Generated by Django 4.1 on 2022-08-26 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='role',
            new_name='role_system',
        ),
    ]
