# Generated by Django 4.1 on 2022-09-06 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_role_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role_system',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
