# Generated by Django 4.1 on 2022-09-06 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_permission_role_alter_projectmember_roles'),
        ('users', '0006_alter_customuser_role_system'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='permissions',
        ),
        migrations.RemoveField(
            model_name='role',
            name='project',
        ),
        migrations.DeleteModel(
            name='permission',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
