# Generated by Django 4.1 on 2022-08-26 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('role_id', models.IntegerField(max_length=100)),
            ],
        ),
    ]
