# Generated by Django 4.1 on 2022-09-08 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_role_permissions_remove_role_project_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['last_name']},
        ),
    ]
