# Generated by Django 4.1 on 2022-09-23 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0002_sprintmember'),
        ('users', '0009_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='sprints',
            field=models.ManyToManyField(through='sprints.SprintMember', to='sprints.sprint'),
        ),
    ]
