# Generated by Django 4.1 on 2022-09-26 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_stories', '0002_userstory_sprint_userstory_sprint_member'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userstory',
            options={'ordering': ['code']},
        ),
    ]
