# Generated by Django 4.1 on 2022-09-27 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_stories', '0003_alter_userstory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userstory',
            options={'ordering': ['id']},
        ),
    ]
