# Generated by Django 4.1 on 2022-10-14 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_stories', '0005_userstory_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstory',
            name='sprint_priority',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
