# Generated by Django 4.1 on 2022-10-14 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_stories', '0005_userstoryhistory'),
        ('user_stories', '0006_userstory_sprint_priority'),
    ]

    operations = [
    ]
