# Generated by Django 4.1 on 2022-10-29 13:26

from django.db import migrations, models
import django.db.models.deletion
import user_stories.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_stories', '0007_merge_20221014_2252'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStoryAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=user_stories.models.us_directory_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_stories.userstory')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
