# Generated by Django 4.1 on 2022-10-28 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_role_name'),
        ('user_stories', '0007_merge_20221014_2252'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStoryComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('project_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projectmember')),
                ('user_story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_stories.userstory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
