# Generated by Django 4.1 on 2022-11-02 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_stories', '0008_userstoryattachment'),
        ('user_stories', '0008_userstorycomment'),
    ]

    operations = [
    ]
