# Generated by Django 4.1 on 2022-11-02 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0002_sprintmember'),
        ('user_stories', '0009_merge_0008_userstoryattachment_0008_userstorycomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStoryTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('column', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('sprint', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sprints.sprint')),
                ('sprint_member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sprints.sprintmember')),
                ('user_story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_stories.userstory')),
            ],
        ),
    ]
