# Generated by Django 4.1 on 2022-11-02 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_stories', '0010_userstorytask'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstorytask',
            name='hours_worked',
            field=models.IntegerField(default=0),
        ),
    ]
