# Generated by Django 4.1 on 2022-11-03 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_stories', '0011_userstorytask_hours_worked'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstory',
            name='hours_worked',
            field=models.IntegerField(default=0),
        ),
    ]
