# Generated by Django 4.1 on 2022-11-03 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_stories', '0012_userstory_hours_worked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstory',
            name='hours_worked',
        ),
    ]
