# Generated by Django 4.1 on 2022-11-03 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_stories', '0013_remove_userstory_hours_worked'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstory',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'En progreso'), ('CANCELLED', 'Cancelado'), ('FINISHED', 'Finalizado')], default='IN_PROGRESS', max_length=15, verbose_name='Estado'),
        ),
    ]
