# Generated by Django 4.1 on 2022-11-04 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_stories', '0014_userstory_status'),
        ('user_stories', '0014_userstorytask_disabled'),
    ]

    operations = [
    ]
