# Generated by Django 4.1 on 2022-11-04 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_projectholiday_date'),
        ('user_stories', '0015_merge_20221104_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstory',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
    ]
