# Generated by Django 4.1 on 2022-09-03 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectmember',
            old_name='role',
            new_name='roles',
        ),
    ]
