# Generated by Django 4.1 on 2022-09-07 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_permission_role_alter_projectmember_roles'),
        ('projects', '0005_userstorytype'),
    ]

    operations = [
    ]
