# Generated by Django 4.1 on 2022-09-07 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_merge_20220907_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Creado'), ('IN_PROGRESS', 'En progreso'), ('CANCELLED', 'Cancelado'), ('FINISHED', 'Finalizado')], default=True, max_length=15),
        ),
    ]
