# Generated by Django 4.1 on 2022-11-03 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_projectholiday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectholiday',
            name='date',
            field=models.DateField(),
        ),
    ]
