# Generated by Django 4.1 on 2022-09-23 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0008_alter_role_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PLANNED', 'Planeado'), ('IN_PROGRESS', 'En progreso'), ('CANCELLED', 'Cancelado'), ('FINISHED', 'Finalizado')], max_length=15, verbose_name='Estado')),
                ('number', models.IntegerField()),
                ('capacity', models.IntegerField(null=True, verbose_name='Capacidad en horas')),
                ('duration', models.IntegerField(null=True, verbose_name='Duración en días')),
                ('start_date', models.DateField(null=True, verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(null=True, verbose_name='Fecha de finalización')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
    ]
