# Generated by Django 3.2.14 on 2022-08-06 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('sent', models.DateTimeField(auto_now_add=True)),
                ('used', models.DateTimeField(null=True)),
            ],
        ),
    ]
