# Generated by Django 4.1 on 2022-08-20 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sga', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invitation',
        ),
    ]
